import { FC } from 'react'
import Head from 'next/head'
import Authorization from '../components/Authorization';

const Home: FC = () => {

  return (
    <>
      <Head>
        <title>Авторизация</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <div className="main__wrapper">
          <div className="container">
            <div className="main__content">
              <Authorization />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default Home;